# Generated by Django 3.2.11 on 2022-01-22 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220122_0252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('is_reader', 'Can only read'), ('is_writer', 'Can read and write'), ('is_admin', 'Can do everything'))},
        ),
    ]
